### ISSUE TITLE
A separate tab for Badges in Header or Footer

### ISSUE THREAD

**Issue by venkateshprabhu2** [18praneeth/sushiksha-website#11]
Currently, to give a badge we have to visit a member profile. There should be a separate menu option on all the pages, preferably under a drop down(profile?) from which any user can select any username and give any badge. 

This requires some work but it has to be done sooner or later.

**Comment by swasthikcnayak** [comment]
I would like to give this a try

**Comment by 18praneeth** [comment]
Sure 😃 
@swasthikcnayak you can take this issue

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/105192092-c6c7c880-5b5d-11eb-8c44-24fc73784112.png)
@venkateshprabhu2 Can I close the issue now
