### ISSUE TITLE
Improving pagination

### ISSUE THREAD

**Issue by swasthikcnayak** [18praneeth/sushiksha-website#112]
**Description.**
In the pagination, the user could only see the current page number and can go to 1 next and back, It would be better if it is possible to switch between more than 1. Let's say I'm on page 4 and I want to go to page 1, I have to press back button 4 times.

**Possible solution**
Adding a first and last page numbers, and skip by more than one pages.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/105350724-98a3c080-5c11-11eb-8015-1b331bfb56f8.png)
Improved the pagination.
