### ISSUE TITLE
Badge list display can be improved

### ISSUE THREAD

**Issue by swasthikcnayak** [18praneeth/sushiksha-website#113]
There is a lot of space being wasted with in the display of all available badges display of while giving badges.
![Capture](https://user-images.githubusercontent.com/55913708/104990028-c3d7b580-5a41-11eb-9ed5-1d3d356e27cf.PNG)

As you can see the left red column space is essentially wasted. Could be made useful or design could be updated.

**Comment by 18praneeth** [comment]
Yeah,
Intially I thought there will be less badges but now the number of badges has increased.
There is a need of changing design
@keerthi-kamath can you work on the design changes

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/106474626-1c3f9600-64cb-11eb-8b10-b1100ccbdcf7.png)
Table display

**Comment by swasthikcnayak** [comment]
This issue still exists in the profile and member details page viewing
badges

**Comment by 18praneeth** [comment]
No ig, I have updated that page as well.
