### ISSUE TITLE
Email icon in user profile

### ISSUE THREAD

**Issue by nabhak25** [18praneeth/sushiksha-website#13]
![Screenshot 2020-11-07 at 21 56 32](https://user-images.githubusercontent.com/36698440/98446540-22c8a680-2144-11eb-9bd5-587e264d1c08.png)

G+ is not so intuitive, replace it with a proper email icon.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/99493695-afb9fe00-2995-11eb-8916-ad17ec2f01d9.png)
#65
