### ISSUE TITLE
Capitalize the head

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#134]
**Describe the bug**
Capitalize the fields in Profile Page

**To Reproduce**
1. Go to 'Profile page'

**Expected behavior**
Capitlization 

**Screenshots**
Capitalize the head
![image](https://user-images.githubusercontent.com/64249185/105353534-5f6d4f80-5c15-11eb-9f17-cb037cd49564.png)

**Comment by dascolt1** [comment]
I can work on this.

**Comment by 18praneeth** [comment]
Sorry @dascolt1, currently we only allow PR from members of our group.
Thanks for showing interest, hope you find other repo where you can find similar issues. ❤️

**Comment by 18praneeth** [comment]
@RishabhNaik can you take up this
