### ISSUE TITLE
Adding website link and Profile link to mail

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#137]
![image](https://user-images.githubusercontent.com/64249185/105399276-6746e700-5c49-11eb-862d-f4ca4aae6dbe.png)
It would easier for users to click on the links from mail and access the website.
Also updating title attribute of IMG tag and adding link to image if needed.

**Comment by 18praneeth** [comment]
@RishabhNaik can you take this issue

**Comment by RishabhNaik** [comment]
Yes

**Comment by 18praneeth** [comment]
#152 #153
