### ISSUE TITLE
Mentee is default for all user profiles, even Mentors

### ISSUE THREAD

**Issue by nabhak25** [18praneeth/sushiksha-website#14]
There is no field to input whether an individual is a Mentee or a Mentor. 
Note: Only Gurudath sir and Venkatesh Prabhu's profile says Mentor, the rest of the mentors has Mentee in their individual profiles.

**Comment by 18praneeth** [comment]
Thanks, @nabhak25 for mentioning this.
In the website, only admin can change the role from mentee to mentor.
I have not permitted updating role in the profile as mentee can make himself as mentor any time and they can award badges which can be only given by mentors.

**Comment by 18praneeth** [comment]
I have updated all the mentor list. 👍

**Comment by nabhak25** [comment]
Sure. I was not aware of that workflow! Thank you for updating the mentor
list! 😊

**Comment by 18praneeth** [comment]
Can I close this issue @venkateshprabhu2 
As of now, I don't have any better solution that can prevent misuse of Mentor badge.
