### ISSUE TITLE
Shared timer for pair sessions

### ISSUE THREAD

**Issue by keerthi-kamath** [18praneeth/sushiksha-website#156]
Please integrate the shared timer, in order to keep track of timings during the pair sessions
Ref: Cuckoo timer - https://cuckoo.team

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/106564700-9a477f80-6553-11eb-85ef-ed888fc1069a.png)
We can implement the feature using the `<iframe>` tag, but it's unreliable we will not have any control over the timer, anyone who has an account on the website, can pause or start the timer, this, in turn, can affect pair sessions.

Closing this issue, if we get a better solution we can reopen it again.
