### ISSUE TITLE
Give a badge page - content updates

### ISSUE THREAD

**Issue by sskini2** [18praneeth/sushiksha-website#16]
Top "Give a badge to XX" section:
1. "Describe why you are giving the badge": Change "your" to "you".
2. Badge dropdown: Don't say Badge for each entry. The title of the dropdown says it's a badge and hence is redundant if you say badge for every entry.  I think the dropdown should also say how many points each badge cost. And finally, I would not capslock the badge names.
Tl;dr : I propose "Angel (1 pt)" for what the current "Badge: ANGEL" should look like

Badge listing (the one with icons)
3. Usually when you say * (for Angel and Rockstar) the immediate response is to see at the bottom of the page (in this case bottom of listing) to see what the * means. I understand it is described in the Red pod on the left, but I think we should have a small "* Mentors only" in the bottom of the listing. 
4. Lets be consistent about using fullstops or not after the badge description. I think we shouldn't have fullstops since its more of a caption and not full sentence. 
5. "BRAIN WAVE: To that buddy who brainstormed my problem with me": Re-writing it a bit.  
6. "EXTRA MILE: To the person who went out of their way to help me": Change "the" to "their".
7. Perhaps change the caption of Gracias to be consistent with other captions: "To the person whom I owe a lot" (its okay to have same caption for both Gracias and Gracias by mentors.
8. "PICTURE PERFECT: To the person who has a beautiful profile picture": again to be consistent.
9. ROCKSTAR *: ROCKSTAR OF SUSHIKSHA: I think making this as exception is fine. However remove "the" before "Sushiksha"
10: "SWISS KNIFE: To that multi-tasker who has solutions for everything": "Multi Tasker" changed to "multi-tasker", "got" to "has", "solution" to "solutions"

Red pod on the left:
11. "Why give a badge?": De-capitalize both Give and Badge
12. "Rules for giving a badge": Instead of "badges" say "a badge"
13. "You cannot give a badge to yourself': Change "for" to "to"
14. "Give a badge only when you feel the person deserves it.": Change "badges" to "a badge".  
15. "A badge with '*' can be given only by the mentors. (rewrote the sentence a bit).

**Comment by 18praneeth** [comment]
Fixed ✔️ #31
