### ISSUE TITLE
Improper badge alignment

### ISSUE THREAD

**Issue by keerthi-kamath** [18praneeth/sushiksha-website#163]
The badge alignment varies as per the title. Try implementing the flip cards to avoid the issues

**Comment by swasthikcnayak** [comment]
@keerthi-kamath Could you elaborate and give a description of when and where the issue is.

**Comment by 18praneeth** [comment]
Is this issue related to mobile view or desktop?
On the desktop it's displaying correctly, it has a slight issue in mobile mode.
@keerthi-kamath If you want to take this issue, please go ahead. 👍

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/106286510-bbfee900-626b-11eb-924d-dce0c10e2065.png)
User will have option to check any user blog posts

Closing this issue.
