### ISSUE TITLE
Blog posts linked to users profile

### ISSUE THREAD

**Issue by RajathPrabhu221** [18praneeth/sushiksha-website#166]
It'll be really helpful if we could link the blog posts written by specific users with their profiles. It'll make it easily accessible by writers.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/106286510-bbfee900-626b-11eb-924d-dce0c10e2065.png)
User will have option to check any user blog posts

Closing this issue.
