### ISSUE TITLE
Integrate Recognitions with Slack

### ISSUE THREAD

**Issue by rosequ** [18praneeth/sushiksha-website#17]
### Why was this issue opened?
Let us make sure messages on the website related to badges get posted on Slack!
![image](https://user-images.githubusercontent.com/8274617/98481922-d3c65400-21cb-11eb-80f6-d6278726d253.png)

**Comment by Kapilshanbhag09** [comment]
@18praneeth we can one thing i.e whenever anyone gives a batch we can call a webhook which can post message in a particular channel in sophists.

**Comment by venkateshprabhu2** [comment]
@Kapilshanbhag09 Would you be able to pick this up?

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/105639451-63f86900-5e9e-11eb-8d5a-d6f01384fb6d.png)
#141

**Comment by 18praneeth** [comment]
Closing this issues
