### ISSUE TITLE
Change the styling of input field

### ISSUE THREAD

**Issue by Kapilshanbhag09** [18praneeth/sushiksha-website#18]
https://user-images.githubusercontent.com/56125734/98500011-45a4a900-2271-11eb-98c7-0c3857437c95.jpg
highlight of the input field on click can be removed by using css property "outline:none;". And the border size can be increased by 1 or 2 pixels

**Comment by Gagan-Shenoy** [comment]
Hey can  I work on this ?

**Comment by venkateshprabhu2** [comment]
> Hey can I work on this ?

Sure. I am assigning this to you. Follow the readme and send a PR to the develop branch.

**Comment by 18praneeth** [comment]
Thanks, @Gagan-Shenoy for resolving this issue.
I will close the issue.
