### ISSUE TITLE
Improve the Readme.md

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#191]
- Align badges to center
- Add detail about Sushiksha
- Write a short contributing guideline that PR is only accepted by Sophists | Sushikha workspace members
- Add more badges if necessary.

**Comment by aditya28sarin** [comment]
Can you asign this issue to me?

**Comment by 18praneeth** [comment]
Sorry @aditya28sarin, We only accept PR's from those who are part of our group.
Thanks for showing interest 😄

**Comment by aditya28sarin** [comment]
No problem, thankyou!

**Comment by swasthikcnayak** [comment]
*Update*
Developers should make a folder /media and put a image default.jpg to avoid errors in creating superuser.

**Comment by 18praneeth** [comment]
Yes, @krishnashenoy123 Please mention this in the Development 

> _Update_
> Developers should make a folder /media and put a image default.jpg to avoid errors in creating superuser.

**Comment by swasthikcnayak** [comment]
settings.py link is incorrect, please rectify
