### ISSUE TITLE
Improper animations in the about file

### ISSUE THREAD

**Issue by krishnashenoy123** [18praneeth/sushiksha-website#195]
- If you check the About page, the VAA description paragraph has the fade right animations while the other two has the fade up animation.
- the VAA paragraph animations appears when we scroll down but the VKSSF paragraph doesnt, it doesnt has delay time.

**Comment by 18praneeth** [comment]
@krishnashenoy123 can you work on this

**Comment by 18praneeth** [comment]
Also, there are other animation issues on the website

**Comment by krishnashenoy123** [comment]
> @krishnashenoy123 can you work on this

Yes I'll try to do it 👍
