### ISSUE TITLE
Fix Edit Profile

### ISSUE THREAD

**Issue by rosequ** [18praneeth/sushiksha-website#2]
### Why was this issue opened?
The `Edit Profile` button is not clear on first sight

### How to reproduce?
![image](https://user-images.githubusercontent.com/8274617/98430874-d5363600-207e-11eb-8ca0-0e9634f2154a.png)

**Comment by 18praneeth** [comment]
Thanks @rosequ , I will work on it

**Comment by srinidhibhat45** [comment]
Can I work on this? I believe changing the font colour should do the trick

**Comment by 18praneeth** [comment]
Yes @srinidhibhat45, You can create a new class for that text and change the colour,
if possible you can add hover effect etc.
