### ISSUE TITLE
Slack metrics reports to team leads

### ISSUE THREAD

**Issue by venkateshprabhu2** [18praneeth/sushiksha-website#20]
Periodic reports about team members' performance in Slack to the team leads.

**Comment by 18praneeth** [comment]
Venky I just checked and slack feature for checking it's analytics is only available for enterprise customers 😞 .

**Comment by venkateshprabhu2** [comment]
Yeah! The API is limited to Enterprise but I think Kapil will work on providing the analytics csv file and generating a report.

**Comment by 18praneeth** [comment]
I can use the website to upload the CSV file monthly and generate that output.

**Comment by venkateshprabhu2** [comment]
@18praneeth Let's wait for Kapil to come up with his plan. Do not do anything for now.

**Comment by 18praneeth** [comment]
@venkateshprabhu2 Ok 👍

**Comment by 18praneeth** [comment]
#141
