### ISSUE TITLE
Improve the UI for badge claim list

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#234]
![image](https://user-images.githubusercontent.com/64249185/107508278-c3f14e00-6bc6-11eb-8d88-6964b9ff5ad1.png)

**Comment by krishnashenoy123** [comment]
@18praneeth Can you brief it out what has to be done ?
Ill do it.

**Comment by AdityaPandey03** [comment]
hey @18praneeth can I work on this?

**Comment by RishabhNaik** [comment]
#327

**Comment by theanmolmalik** [comment]
Hi, I am very much interested to fix this issue. Can you please assign it to me?

**Comment by 18praneeth** [comment]
This issue is fixed, sorry everyone for late reply, somehow I missed the notification
