### ISSUE TITLE
Add a <div> tag for image, text display below the image should be avoided in top-mention section

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#235]
![image](https://user-images.githubusercontent.com/64249185/107508542-32361080-6bc7-11eb-82b9-fd23876771ea.png)

**Comment by krishnashenoy123** [comment]
Can i know this issue in detail 
@swasthikcnayak / @18praneeth

**Comment by 18praneeth** [comment]
There are text under the image like NOV 20 is under the badge logo, you have to make a separate box for text and image
