### ISSUE TITLE
Remove the extra indent in the Profile page buttons

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#241]
![image](https://user-images.githubusercontent.com/64249185/107603916-5855c200-6c54-11eb-9807-e620bc925c61.png)

**Comment by kangkanjr** [comment]
I will work on this.

**Comment by swasthikcnayak** [comment]
Sorry, @kangkanjr  We only accept PR's from those who are part of our group.
Thanks for showing interest, good luck in contributing to other repos,
Happy coding 😃

**Comment by kangkanjr** [comment]
sure
