### ISSUE TITLE
Fix Placeholder typo in the Award a Badge page.

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#243]
Description placeholder should be changed from 
`Describe why your are giving the badge` to
`Describe why you are giving the badge`
![image](https://user-images.githubusercontent.com/64249185/107733218-74269a00-6d20-11eb-9800-53a7445792d7.png)

Page URLs in localhost:
/user/badge/
/user/badge/<id> of user/

**Comment by 18praneeth** [comment]
@krishnashenoy123 can you take this up?

**Comment by krishnashenoy123** [comment]
Ok I'll do it 👍
