### ISSUE TITLE
Change message from warning to success.

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#246]
After awarding a badge to the user, it shows your badge is under review, change the message to your badge has been awarded or something similar.
To fix this issue:
Go to users/views.py: https://github.com/18praneeth/sushiksha-website/blob/48df7b2d9f3ae342a3e190b94b6a307faff613d5/users/views.py#L199
Change the message type to success

**Comment by 18praneeth** [comment]
https://github.com/18praneeth/sushiksha-website/blob/48df7b2d9f3ae342a3e190b94b6a307faff613d5/users/views.py#L230

It has to be changed in 2 position

**Comment by krishnashenoy123** [comment]
Ok I'll do it

**Comment by 18praneeth** [comment]
Sure you can take up the issue

**Comment by 18praneeth** [comment]
```python
message.success(request, 'message here')
```
Don't forget to change the message type from info to success

**Comment by 18praneeth** [comment]
#247
