### ISSUE TITLE
Add a Mass Badge Distribution option

### ISSUE THREAD

**Issue by srinidhibhat45** [18praneeth/sushiksha-website#273]
**Is your feature request related to a problem? Please describe.**

Giving badges to contests is extremely tedious and difficult because of the fact that each one has to be given individually.

**Describe the solution you'd like**

A nice interface to give similar badges to a large number of people at once and easily without having to do it individually per person

**Describe alternatives you've considered**

Givin it to each one indivisually.

**Additional context**

**Comment by swasthikcnayak** [comment]
It's already implemented, but is available only to admin for now, will come up with a solution soon

**Comment by srinidhibhat45** [comment]
sure okay!

**Comment by swasthikcnayak** [comment]
@srinidhibhat45 this issue has been addressed, if the requirement is met, please close the issue.

**Comment by srinidhibhat45** [comment]
@swasthikcnayak thank you :)
