### ISSUE TITLE
Team/House Identifier in the individual member Profiles

### ISSUE THREAD

**Issue by gurubaliga** [18praneeth/sushiksha-website#32]
It is desirable to have Team Identifier in the individual profiles of members. We can know which team the member belongs to.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/99391691-8e5b0280-2900-11eb-9903-6967b41dd855.png)
Now when viewing members profile it shows, house name, team name with Points scored
Attaching image as a referance.

**Comment by swasthikcnayak** [comment]
The team, house and points details of the logged-in user are not visible.  ( I can see others' details but not mine)
