### ISSUE TITLE
Blog post tags won't work. 

### ISSUE THREAD

**Issue by sushiksha-wkc** [18praneeth/sushiksha-website#4]

**Comment by sushiksha-wkc** [comment]
<img width="1678" alt="Screenshot 2020-11-07 at 10 51 33 AM" src="https://user-images.githubusercontent.com/73731177/98432741-5f19e980-20e7-11eb-8364-d7492a7ee694.png">
<img width="1663" alt="Screenshot 2020-11-07 at 10 51 23 AM" src="https://user-images.githubusercontent.com/73731177/98432742-63de9d80-20e7-11eb-94d5-8f005bce4843.png">

**Comment by sushiksha-wkc** [comment]
Clicking on the 'Education' tag in above post for example gives me a 500 error.

**Comment by swasthikcnayak** [comment]
I would like to work on this bug, also the categories links aren't working in the right side of blogs, would like to work on both these.

**Comment by 18praneeth** [comment]
Sure 😃
@swasthikcnayak you can work on it.

**Comment by 18praneeth** [comment]
#95
