### ISSUE TITLE
Website Optimization 

### ISSUE THREAD

**Issue by yeltsinxyz** [18praneeth/sushiksha-website#42]
Hello everyone 🖖 

I was checking GitHub for labels under `good first issue` but I also want to help sharing some website optimizations tips.

### Image Resize

This image: https://sushiksha.konkanischolarship.com/media/blog-post-thumbnail/SCL_Wall_Paper_Wide.jpg has a whooping 3.3 MB size. It's enormous. Even with a 4K monitor, it's big. I used Cloudinary with JPEG Mini to compress and resize the photo and it's down to 228 KB 😄

![SCL_Wall_Paper_Wide_yj3jn7](https://user-images.githubusercontent.com/28705239/98891728-8c66ee80-247d-11eb-9ecf-c1563fb0555a.jpg)

I also resized this one: https://sushiksha.konkanischolarship.com/media/blog-post-thumbnail/Sushiksha_Logo.jpg, from 817 KB to 218 KB.

![Sushiksha_Logo_tmzakq](https://user-images.githubusercontent.com/28705239/98891742-925ccf80-247d-11eb-9c95-2119395d540a.jpg)

### A LOT of icon font

So you are using three icon fonts:

…icofont/icofont.min.css(sushiksha.konkanischolarship.com) | 25.3 KiB | 270 ms
…css/boxicons.min.css(sushiksha.konkanischolarship.com) | 22.3 KiB | 270 ms
…remixicon/remixicon.css(sushiksha.konkanischolarship.com) | 14.6 KiB | 230 ms

My suggestion is to stick with one. 

### Font Optimization

I suggest you put your font loading on "swap". You can check out more about this property on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display). 

### Lighthouse Report

I generated a PDF with [Lighthouse](https://developers.google.com/web/tools/lighthouse/) recommendations. 😄 

[lighthouse-big-report.pdf](https://github.com/18praneeth/sushiksha-website/files/5528076/lighthouse-big-report.pdf)

**Comment by 18praneeth** [comment]
Hi 👋 ,
Thanks for your valuable feedback, as this issue is already mentioned by one of our collaborators, I am closing this issue. #49
