### ISSUE TITLE
Data is incorrect for a given team

### ISSUE THREAD

**Issue by nabhak25** [18praneeth/sushiksha-website#46]
Refer screenshots.
![Screenshot 2020-11-12 at 21 23 34](https://user-images.githubusercontent.com/36698440/98963183-600aab00-252d-11eb-95d6-7b60c9e700a6.png)
![Screenshot 2020-11-12 at 21 22 05](https://user-images.githubusercontent.com/36698440/98963200-639e3200-252d-11eb-8eef-9253e9fee285.png)
 
Random issue, will add more details of reproducing this if I find.

**Comment by nabhak25** [comment]
Steps to reproduce - 
Click Leaderboard
Click any House
Click on any mentee profile
Give any badge
Click on Leaderboard from the current page
Select the previously selected house
Now the data is mismatched

Please Note: **Happens randomly**

**Comment by 18praneeth** [comment]
Yes, @nabhak25 
The top 4 buttons are not working correctly, but if you keep on changing it becomes correct 😕 
Thanks will look into it.
