### ISSUE TITLE
Members display page

### ISSUE THREAD

**Issue by SSPai123** [18praneeth/sushiksha-website#48]
- In Members page, you can have 2 tabs named - Mentees and Mentors and display profiles accordingly based on role.
The main idea is to have easier segregation/filtering of profiles.
- Display profiles in the alphabetically sorted manner in each tab.

**Comment by venkateshprabhu2** [comment]
@18praneeth I would like this one to be fast tracked. Strictly speaking, it would be better if we can expose Mentor tab to everyone and not expose their email id or private info. May be a photo with a name and the company that they are working for and the job title.

**Comment by 18praneeth** [comment]
Ok then, I will work on this feature.

**Comment by 18praneeth** [comment]
I can also add pagination if you want.

**Comment by venkateshprabhu2** [comment]
Pagination for 20 mentors? Not necessary I guess. :) Please show a quick demo(local will do for now) to me before pushing to live. Not super urgent but when you have some time. :)

**Comment by 18praneeth** [comment]
Yeah got it.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/100384343-f5d22a00-3045-11eb-8dd9-e99370b15585.png)
I have added a separate tab for mentee and mentors, can I close this issue now @venkateshprabhu2

**Comment by venkateshprabhu2** [comment]
"Pagination for 20 mentors? Not necessary I guess. :) Please show a quick demo(local will do for now) to me before pushing to live. Not super urgent but when you have some time. :)" 

@18praneeth Above was my last comment. I would have appreciated if you had showed me the demo before pushing live(as you agreed to). Now that it's live, feel free to close whatever seems fit.

**Comment by 18praneeth** [comment]
Sorry @venkateshprabhu2 , I worked on 3 issues together, completely forgot to show you the screenshot, I will try to enhance the tabs.
