### ISSUE TITLE
Leaderboard sorter is shifted by one column

### ISSUE THREAD

**Issue by sskini2** [18praneeth/sushiksha-website#50]
i.e. If I sort by badge count then the user name gets sorted. If I try to sort by points, it sorts by badge count.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/99189044-38ae1b00-2785-11eb-9f00-50b471ccefc9.png)
Can you check once, it's working fine for me.

**Comment by sskini2** [comment]
Note: The points there are 45, 37, 30, 17, 22, 36 which is not descending order of points.

**Comment by 18praneeth** [comment]
It is sorted with Number of badges.

**Comment by sskini2** [comment]
but you have clicked on sorting by points (thats what is selected in the screenshot)

**Comment by 18praneeth** [comment]
No, the first sortable arrow marks are for user column and second for badge count.

**Comment by sskini2** [comment]
Ohhhh... I think it is an UX issue then. Since the distance of sorter is closer to the next column, it is confusing. Perhaps we can move it closer to the name?

**Comment by venkateshprabhu2** [comment]
@18praneeth Is this requirement clear? How big of an effort is this? Also, is this related to the front end code or Python?

**Comment by 18praneeth** [comment]
It's related to datatable.js, it's difficult to modify that
I can add a line in between each column.

**Comment by 18praneeth** [comment]
![image](https://user-images.githubusercontent.com/64249185/99705567-e855f680-2abf-11eb-9805-cb14bca2fc20.png)

**Comment by venkateshprabhu2** [comment]
@sskini2 Would adding that line in between be helpful? Otherwise, we will see what we can do and add this to the backlog for now.

**Comment by sskini2** [comment]
I like the line. I think it will definitely be less ambiguous

**Comment by venkateshprabhu2** [comment]
@18praneeth Let's add that line in our next push. Also, let's start pushing out multiple features/bug fixes together from now on and do a deployment once in a week or so (Critical & emergency fixes excluded). If possible, let's set the next release date to upcoming Sunday. Do not push even if you are ready before that. If you have extra time, work on other tougher issues, may be.

**Comment by 18praneeth** [comment]
@venkateshprabhu2 we can have our next release on 29th

**Comment by 18praneeth** [comment]
#75 Solved this issue in recent PR, closing the issue
