### ISSUE TITLE
Reduce the Resolution of the image when user creates a blog post.

### ISSUE THREAD

**Issue by 18praneeth** [18praneeth/sushiksha-website#59]
The Thumbnail images of the blog are taking too much time to load.
![image](https://user-images.githubusercontent.com/64249185/99401260-ff54e700-290d-11eb-8439-8a1b19516fcd.png)
![image](https://sushiksha.konkanischolarship.com/media/blog-post-thumbnail/SCL_Wall_Paper_Wide.jpg)

**Comment by imrushikesh** [comment]
you can try WebP or convert jpg images to WebP.

**Comment by 18praneeth** [comment]
Now Site support Image compression as mentioned in PR #69
