### ISSUE TITLE
Wrong mail icon in footer

### ISSUE THREAD

**Issue by venkateshprabhu2** [18praneeth/sushiksha-website#6]
<img width="1663" alt="Screenshot 2020-11-07 at 10 51 23 AM" src="https://user-images.githubusercontent.com/5301059/98433132-465f0300-20ea-11eb-971f-3387341a925b.png">

Clicking on the skype icon is opening mailbox in laptop. I am assuming it's supposed to be a mail icon.

**Comment by 18praneeth** [comment]
Issue got resolved ✔️
