### ISSUE TITLE
Testimonials and Blog Update shows nothing underneath after Logout

### ISSUE THREAD

**Issue by SSPai123** [18praneeth/sushiksha-website#76]
Steps to recreate:
- Login to the website
- Logout from the website
- Scroll down, you will see that there is no data below Latest Update and Testimonials as shown in image below.

![image](https://user-images.githubusercontent.com/28781009/100497766-8eba8f80-3183-11eb-96d2-c8de634816bd.png)

**Comment by swasthikcnayak** [comment]
I would like to take this up
